### Eliminación Gaussiana

Resolver por eliminación Gaussiana el siguiente sistema de ecuaciones

$$3x_1 - 0.1x_2 - 0.2x_3 = 7.85$$
$$0.1x_1  + 7x_2 - 0.3x_3 = -19.3$$
$$0.3x_1 - 0.2x_2 + 10x_3 = 71.4$$

#### Desarrollo de *script*

In [5]:
import numpy as np

# Matrix creation
A = np.matrix([[3, -0.1, -0.2, 0.1, 7.85], \
               [0.1, 7, -0.3, 1, -19.3], \
               [0.3, -0.2, 10, 24, 71.4], \
               [8, -2, 1, 0.1, 4]])

# Get dimensions of matrix
n, m = A.shape
print("Number of incognites =", n)

# Forward elimination
for i in range(n - 1):
    for j in range(i + 1, n):
        factor = A[j, i]/A[i, i]
        for k in range(i, n + 1):
            A[j, k] = A[j, k] - factor*A[i, k]
    print("\n\nReduction number {}\n".format(i + 1), A)

# Backward sustitution
solutions = np.zeros(n)
solutions[-1] = A[n - 1, m - 1]/A[n - 1, n - 1]
for i in reversed(range(n - 1)):
    sumatory = 0
    for j in reversed(range(i + 1, n)):
        sumatory = sumatory + A[i, j]*solutions[j]
    solutions[i] = (A[i, m - 1] - sumatory)/A[i, i]

# Print solutions
print("\n\nSolution:")
for i in range(n):
    print("x_{} =".format(i), solutions[i])

Number of incognites = 4


Reduction number 1
 [[  3.          -0.1         -0.2          0.1          7.85      ]
 [  0.           7.00333333  -0.29333333   0.99666667 -19.56166667]
 [  0.          -0.19        10.02        23.99        70.615     ]
 [  0.          -1.73333333   1.53333333  -0.16666667 -16.93333333]]


Reduction number 2
 [[  3.          -0.1         -0.2          0.1          7.85      ]
 [  0.           7.00333333  -0.29333333   0.99666667 -19.56166667]
 [  0.           0.          10.01204188  24.0170395   70.08429319]
 [  0.           0.           1.46073298   0.08000952 -21.77486911]]


Reduction number 3
 [[ 3.00000000e+00 -1.00000000e-01 -2.00000000e-01  1.00000000e-01
   7.85000000e+00]
 [ 0.00000000e+00  7.00333333e+00 -2.93333333e-01  9.96666667e-01
  -1.95616667e+01]
 [ 0.00000000e+00  0.00000000e+00  1.00120419e+01  2.40170395e+01
   7.00842932e+01]
 [ 0.00000000e+00  0.00000000e+00  2.22044605e-16 -3.42401915e+00
  -3.20000000e+01]]


Solution:
x_0 = 1.11

#### La siguiente imagen explica cómo se toman los índices durante el proceso de *Forward elimination*

<img src="files/Matrix_index.png">

#### Aquí se explica el proceso *Backward sustitution*

<img src="files/backward_sustitution.png">

### Alternativas a nuestro *script*

Python en sus librerías ofrece un amplia gama de algoritmos precargados. Para este tema dentro de *numpy* existe una herramienta que resuelve sistemas de ecuaciones algebraicas lineales

A continuación el uso de esta herramienta.

In [3]:
import numpy as np

A = np.matrix([[3, -0.1, -0.2], \
               [0.1, 7, -0.3], \
               [0.3, -0.2, 10]])

b = np.matrix([7.85, -19.3, 71.4])

x = np.linalg.solve(A, b.transpose())

print(x)

[[ 3. ]
 [-2.5]
 [ 7. ]]
